news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB, GiornalistaListView, giornalisti_list_api, articoli_list_api, giornalista_api, articolo_api, tabella_giornalisti, tabella_articoli #articoloDetailView

app_name= 'news'

urlpatterns=[
    path('',home, name="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    #path("lista_giornalisti/", ArticoloListView.as_view(), name="lista_giornalisti")
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti"),

    path("giornalisti_list_api/", giornalisti_list_api,name="giornalisti_list_api"),
    path("articoli_list_api/", articoli_list_api,name="articoli_list_api"),
    path("giornalista_api/<int:pk>", giornalista_api,name="giornalista_api"),
    path("articolo_api/<int:pk>", articolo_api,name="articolo_api"),
    path("tabella_giornalisti/", tabella_giornalisti,name="tabella_giornalisti"),
    path("tabella_articoli/", tabella_articoli,name="tabella_articoli"),

]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_generale

urlpatterns = [
    path('',index_generale, name="index_generale"),
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls",namespace="prova_pratica_0")),
    path('news/',include("news.urls",namespace="news")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

prova_pratica_0/urls.py
from django.urls import path
from prova_pratica_0.views import somma,index3,media

app_name="prova_pratica_0"
urlpatterns=[
    path('', index3, name='index3'),
    path('somma',somma,name='somma'),
    path('media',media,name='media')

]

prova_pratica_0/views.py
from multiprocessing import context
import random
from django.shortcuts import render

def somma(request):
    n1=random.randint(1,10)
    n2=random.randint(1,10)
    context={
        'n1':n1,
        'n2':n2,
        's': n1 + n2
    }
    return render(request,"maxmin.html",context)

def media(request):
    lista=[]
    for i in range(30):
        lista.append(random.randint(1,10))
    context={
        'lista':lista,
        'media': sum(lista)/len(lista)
    }
    return render(request,"media.html",context)

def index3(request):
    return render(request,"index3.html")

prova_pratica_0/templates/index3.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | index{% endblock title %} 

{% block content %}
<ol>
    <li><a href="{% url 'prova_pratica_0:somma'%}">Somma</a></li>
    <li><a href="{% url 'prova_pratica_0:media'%}">Media</a></li>
</ol>

{% endblock content %}

prova_pratica_0/templates/maxmin.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | somma{% endblock title %} 

{% block content %}

<h1>Somma</h1>
{% if  n1 < n2 %}
<font color="red">{{ n1 }}</font>
<p>+</p>
<font color="green">{{ n2 }}</font>
{% elif n1 > n2 %}
<font color="red">{{ n2 }}</font>
<p>+</p>
<font color="green">{{ n1 }}</font>
{% else %}
<font color="black">{{ n1 }}</font>
<p>+</p>
<font color="black">{{ n2 }}</font>
{% endif %}
<p>=</p>
<p>{{ s }}</p>

{% endblock content %}

prova_pratica_0/templates/media.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | media{% endblock title %} 

{% block content %}
<h1>Media</h1>
{% for i in lista %}
    {{ i }}
{% endfor %}

{% if media < 6 %}
<br><font color="red">{{ media }}</font>
{% elif media > 6 %}
<br><font color="green">{{ media }}</font>
{% else %}
<br><font color="black">{{ media }}</font>
{% endif %}
{% endblock content %}