news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB, GiornalistaListView, giornalisti_list_api, articoli_list_api, giornalista_api, articolo_api, tabella_giornalisti, tabella_articoli #articoloDetailView

app_name= 'news'

urlpatterns=[
    path('',home, name="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    #path("lista_giornalisti/", ArticoloListView.as_view(), name="lista_giornalisti")
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti"),

    path("giornalisti_list_api/", giornalisti_list_api,name="giornalisti_list_api"),
    path("articoli_list_api/", articoli_list_api,name="articoli_list_api"),
    path("giornalista_api/<int:pk>", giornalista_api,name="giornalista_api"),
    path("articolo_api/<int:pk>", articolo_api,name="articolo_api"),
    path("tabella_giornalisti/", tabella_giornalisti,name="tabella_giornalisti"),
    path("tabella_articoli/", tabella_articoli,name="tabella_articoli"),

]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_generale

urlpatterns = [
    path('',index_generale, name="index_generale"),
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls",namespace="prova_pratica_0")),
    path('news/',include("news.urls",namespace="news")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if,if_else_elif,ciclo_for,index2

app_name="seconda_app"
urlpatterns=[
    path('es_if',es_if,name="es_if"),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('ciclo_for',ciclo_for,name='ciclo_for'),
    path('index2',index2,name='index2'),
]

seconda_app/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def es_if(request):
    context={
        'var1':200,
        'var2':200,
        'var3':300,
    }
    return render(request, "es_if.html",context)

def if_else_elif(request):
    context={
        'var1':100,
        'var2':100.0,
        'var3':100.50,
    }
    return render(request, "if_else_elif.html",context)

def ciclo_for(request):
    context={
        'list1': [1, datetime.date(2019,7,16), 'Do not give up!'],
        'list2': [1, datetime.date(2019,7,16), 'Do not give up!']
    }
    return render(request, "ciclo_for.html",context)


def index2(request):
    return render(request, "index2.html")

seconda_app/templates/ciclo_for.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | ciclo For{% endblock title %} 

{% block content %}
    Clicca una sequenza usando <b>forloop.counter</b>
    <br/>
    {% for x in list2 %}
        <i>{{ forloop.counter }} </i> : {{ x }}<br>
    {% endfor %}
    <br/>
    Clicca una sequenza usando <b>forloop.counter0</b>
    <br/>
    {% for x in list2 %}
        <i>{{ forloop.counter0 }} </i> : {{ x }}<br>
    {% endfor %}
    <br>
    Stampa il primo elemento della sequenza usando <b>forloop.first</b>:
    <br>
    {% for x in list2 %}
        {% if forloop.first %}
            <i>Il primo elemento</i> - {{ x }}
        {% endif %}
    {% endfor %}
    <br>
    Stampa l'ultimo elemento della lista usando <b>forloop.last</b>:
    <br>
    {% for x in list2 %}
        {% if forloop.last %}
            <i>L'ultimo elemento</i> - {{ x }}
        {% endif %}
    {% endfor %}
    <br>


{% endblock content %}

seconda_app/templates/es_if.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | es if{% endblock title %} 

{% block content %}
    <b>var1 ={{ var1 }}</b> <br/>
    <b>var2 ={{ var2 }}</b> <br/>
    <b>var3 ={{ var3 }}</b> <br/>
    {% if var1 < var2 %}
        <p><i>var1 è minore di var2 </i></p>
    {% endif %}
    {% if var1 > var2%}
        <p><i>var1 è maggiore di var2 </i></p>
    {% endif %}
    {% if var1 <= var2%}
        <p><i>var1 è minore o uguale di var2 </i></p>
    {% endif %}
    {% if var1 >= var2%}
        <p><i>var1 è maggiore o uguale di var2 </i></p>
    {% endif %}
    {% if var1 == var2%}
        <p><i>var1 è uguale di var2 </i></p>
    {% endif %}
    {% if var1 != var2%}
        <p><i>var1 è diversa di var2 </i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3%}
        <p><i>var1 è minore di var2 e var1 è minore di var3</i></p>
    {% endif %}
    {% if var1 < var2 or var1 < var3%}
        <p><i>var1 è minore di var2 o var1 è minore di var3</i></p>
    {% endif %}
    {% if not var1 > var2 %}
        <p><i>var1 non è maggiore di var2</i></p>
    {% endif %}


{% endblock content %}

seconda_app/templates/if_else_elif.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | if esle elif{% endblock title %} 

{% block content %}
    <b>var1 ={{var1}}</b> <br/>
    <b>var2 ={{var2}}</b> <br/>
    <b>var3 ={{var3}}</b> <br/>

    {% if var1 < var2 %}
        <p><i>var1 è minore di var2</i></b>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></b>
    {% else %}
        <p><i>var1 è uguale a var2</i></b>
    {% endif %}

    {% if var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% elif var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale a var2</i></b>
    {% endif %}

    {% if var1 <= var2 %}
        <p><i>var1 è minore o uguale a var2</i></p>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% endif %}

    {% if var1 >= var2 %}
        <p><i>var1 è maggiore o uguale a var2</i></p>
    {% elif var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% endif %}

    {% if var1 == var2 %}
        <p><i>var1 è uguale a var2</i></p>
    {% elif var1 != var2 %}
        <p><i>var1 è diverso di var2</i></p>
    {% endif %}

    {% if var1 < var2 and var1 < var3 %}
        <p><i>var1 è minore di var2 e var1 è minore di var3</i></p>
    {% elif var1 > var2 and var1 > var3 %}
        <p><i>var1 è maggiore di var2 e var1 è maggiore di var3</i></p>
    {% endif %}

    {% if not var1 > var2 %}
        <p><i>var1 non è maggiore di var2</i></p>
    {% elif not var1 < var2 %}
        <p><i>var1 non è minore di var2 </i></p>
    {% else %}
        <p><i>var1 è uguale di var2 </i></p>    
    {% endif %}


    
{% endblock content %}

seconda_app/templates/index2.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | index2{% endblock title %} 

{% block content %}
    <ol>
        <li><a href="{% url 'seconda_app:es_if'%}">Es if</a></li>
        <li><a href="{% url 'seconda_app:if_else_elif'%}">if else elif</a></li>
        <li><a href="{% url 'seconda_app:ciclo_for'%}">ciclo_for</a></li>
    </ol>
{% endblock content %}