news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB, GiornalistaListView, giornalisti_list_api, articoli_list_api, giornalista_api, articolo_api, tabella_giornalisti, tabella_articoli #articoloDetailView

app_name= 'news'

urlpatterns=[
    path('',home, name="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    #path("lista_giornalisti/", ArticoloListView.as_view(), name="lista_giornalisti")
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti"),

    path("giornalisti_list_api/", giornalisti_list_api,name="giornalisti_list_api"),
    path("articoli_list_api/", articoli_list_api,name="articoli_list_api"),
    path("giornalista_api/<int:pk>", giornalista_api,name="giornalista_api"),
    path("articolo_api/<int:pk>", articolo_api,name="articolo_api"),
    path("tabella_giornalisti/", tabella_giornalisti,name="tabella_giornalisti"),
    path("tabella_articoli/", tabella_articoli,name="tabella_articoli"),

]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,variabili,index

app_name="prima_app"
urlpatterns=[
    path('', homepage, name='home'),
    path('welcome',welcome,name='welcome'),
    path('lista',lista,name='lista'),
    path('chi_siamo',chi_siamo,name='chi_siamo'),
    path('variabili',variabili,name='variabili'),
    path('index',index,name='index'),

]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_generale

urlpatterns = [
    path('',index_generale, name="index_generale"),
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls",namespace="prova_pratica_0")),
    path('news/',include("news.urls",namespace="news")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request,'homepage.html')

def welcome(request):
    return render(request, 'welcome.html')

def lista(request):
    return render(request, 'lista.html')

def chi_siamo(request):
    return render(request, 'chi_siamo.html')

def variabili(request):
    context={
        'var1': 'Prima variabile',
        'var2': 'Seconda variabile',
        'var3': 'Terza variabile'
    }
    return render(request, "variabili.html",context)

def index(request):
    return render(request, "index.html")

prima_app/templates/chi_siamo.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | chi Siamo{% endblock title %} 

{% block content %}
    <h1>Chi Siamo</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid atque molestiae at totam est sunt dolor minima consequatur a, non illum. Accusantium sequi sunt omnis repudiandae est amet architecto placeat.</p>
{% endblock content %}

prima_app/templates/homepage.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | Homepage {% endblock title %} 

{% block content %}
    <h1>benvenuto</h1>
{% endblock content %}

prima_app/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %} {{block.super}} | index{% endblock title %} 

{% block content %}
    <ol>
        <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a> </li>
        <li><a href="{% url 'prima_app:welcome'%}">welcome</a> </li>
        <li><a href="{% url 'prima_app:lista'%}">lista</a> </li>
        <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a> </li>
        <li><a href="{% url 'prima_app:variabili'%}">Variabili</a> </li>
    </ol>
{% endblock content %}

prima_app/templates/lista.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | Lista{% endblock title %} 

{% block content %}
    <ol><li>Primo</li><li>Secondo</li><li>Terzo</li></ol>
{% endblock %}

prima_app/templates/variabili.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | variabili{% endblock title %} 

{% block content %}
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{% endblock %}

prima_app/templates/welcome.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | Welcome{% endblock title %} 

{% block content %}
    <h1>Welcome</h1>
{% endblock content %}