news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB, GiornalistaListView, giornalisti_list_api, articoli_list_api, giornalista_api, articolo_api, tabella_giornalisti, tabella_articoli #articoloDetailView

app_name= 'news'

urlpatterns=[
    path('',home, name="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    #path("lista_giornalisti/", ArticoloListView.as_view(), name="lista_giornalisti")
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti"),

    path("giornalisti_list_api/", giornalisti_list_api,name="giornalisti_list_api"),
    path("articoli_list_api/", articoli_list_api,name="articoli_list_api"),
    path("giornalista_api/<int:pk>", giornalista_api,name="giornalista_api"),
    path("articolo_api/<int:pk>", articolo_api,name="articolo_api"),
    path("tabella_giornalisti/", tabella_giornalisti,name="tabella_giornalisti"),
    path("tabella_articoli/", tabella_articoli,name="tabella_articoli"),

]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,variabili,index

app_name="prima_app"
urlpatterns=[
    path('', homepage, name='home'),
    path('welcome',welcome,name='welcome'),
    path('lista',lista,name='lista'),
    path('chi_siamo',chi_siamo,name='chi_siamo'),
    path('variabili',variabili,name='variabili'),
    path('index',index,name='index'),

]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_generale

urlpatterns = [
    path('',index_generale, name="index_generale"),
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls",namespace="prova_pratica_0")),
    path('news/',include("news.urls",namespace="news")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

prova_pratica_0/urls.py
from django.urls import path
from prova_pratica_0.views import somma,index3,media

app_name="prova_pratica_0"
urlpatterns=[
    path('', index3, name='index3'),
    path('somma',somma,name='somma'),
    path('media',media,name='media')

]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if,if_else_elif,ciclo_for,index2

app_name="seconda_app"
urlpatterns=[
    path('es_if',es_if,name="es_if"),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('ciclo_for',ciclo_for,name='ciclo_for'),
    path('index2',index2,name='index2'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Primo Progetto</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/"> <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Prima app
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/prima_app/index">Index</a>
                        <a class="dropdown-item" href="/prima_app/homepage">Homepage</a>
                        <a class="dropdown-item" href="/prima_app/welcome">welcome</a>
                        <a class="dropdown-item" href="/prima_app/chi_siamo">Chi siamo</a>
                        <a class="dropdown-item" href="/prima_app/lista">lista</a>
                        <a class="dropdown-item" href="/prima_app/variabili/">Variabili</a>

                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Seconda app
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/seconda_app/es_if">if</a>
                        <a class="dropdown-item" href="/seconda_app/if_else_elif">if else elif</a>
                        <a class="dropdown-item" href="/seconda_app/ciclo_for">ciclo for</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                     data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      News
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/news/tabella_articoli/">Tabella Articoli</a>
                      <a class="dropdown-item" href="/news/tabella_giornalisti/">Tabella Giornalisti</a>
                  </div>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navabarDropdown">
                  <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Esci</a>
                  </div>
                </li>
              {% else %}
              <!-- 
                <li class="nav-item">
                  <a class="nav-link" href="/accounts/logout">registrati</a>
                </li>
              -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {% endif %}
          </ul>
          
        </div>
      </nav>
      <div class="container my-4">
        {% block content %}
        {% endblock content %}
        {% block script %}
        {% endblock script %}
      </div>
  </body>
</html>

templates/index_generale.html
{% extends "base.html" %}

{% block title %} {{block.super}} | index generale {% endblock title%}
{% block content%}
    <ol>
        <li><a href="/admin">admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">prima_app</a></li>
        <li><a href="{% url 'seconda_app:index2'%}">seconda_app</a></li>
        <li><a href="{% url 'prova_pratica_0:index3'%}">prova_pratica_0</a></li>
    </ol>
{% endblock content %}